FROM node:18-slim

# Create app directory
WORKDIR /usr/src/app

#VOLUME express-example/ ./

 RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev


EXPOSE 3000

CMD [ "node", "app.js"]